project:
  type: manuscript
  preview:
    port: 4681

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    toc: true
    toc-depth: 4
    toc-expand: 3
    toc-title: "Table of Contents"
    toc-location: right

  docx: default
  jats: default

  # (other formats)
  # pdf: default
engine: knitr
execute:
  freeze: true

render:
  - "*.qmd"
  - "!sections/"
