project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    toc-location: right

  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true

render:
  - "*.qmd"
  - "!sections/"
